[project]
name = "komagataella"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "biopython>=1.86",
    "great-tables>=0.20.0",
    "pandas>=2.3.3",
]
